services:
  urlshortener.database:
    image: postgres:latest
    container_name: urlshortener.database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # volumes:
    #  - ./.containers/urlshortener-db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432