// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrlShortenerBack.DbContexts;

#nullable disable

namespace UrlShortenerBack.Migrations
{
    [DbContext(typeof(UrlContext))]
    [Migration("20250531181550_LongUrlSize")]
    partial class LongUrlSize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UrlShortenerBack.Models.Url", b =>
                {
                    b.Property<string>("ShortUrl")
                        .HasMaxLength(8)
                        .HasColumnType("VARCHAR(8)")
                        .HasColumnName("ShortUrl");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("LongUrl")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("LongUrl");

                    b.Property<int>("UsedCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UsedCount");

                    b.HasKey("ShortUrl");

                    b.ToTable("Urls", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
